import type { AppProps } from "next/app";
import Script from "next/script";
import Head from "next/head";
import { useEffect } from "react";
import { DDTheme } from "@cnerylozada/dd.front.react.wp.library";
import {
  StoreProvider,
  reducer,
  initialState,
  useStore,
  setTheme,
  setLanguage,
} from "../store";
import { Footer, Navbar } from "../components";
import { languages } from "../utils";
import "../styles/globals.css";

const WrapperApp = ({ children }: { children: any }) => {
  const [store, dispatch] = useStore();

  useEffect(() => {
    const ddLng = localStorage.getItem("dd-lng");
    const ddTheme = localStorage.getItem("dd-theme");
    if (!!ddLng) dispatch(setLanguage(ddLng));
    if (!!ddTheme) dispatch(setTheme(ddTheme === "dark"));
  }, []);

  return (
    <div className={`relative ${store.ddIsDarkMode ? "darkPalette" : ""}`}>
      <Head>
        <title>
          {store.ddLanguage === languages.spanish
            ? "Dynamic Devs - Desarrollo de Software e Innovación"
            : "Dynamic Devs - Software Development & Innovation"}
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script
        type="module"
        src="https://sources-dynamic-devs-icons.vercel.app/build/dynamic-devs-icons.esm.js"
      />
      <Script
        noModule={true}
        src="https://sources-dynamic-devs-icons.vercel.app/build/dynamic-devs-icons.js"
      />
      <DDTheme isDarkMode={store.ddIsDarkMode}>
        <Navbar />
        {children}
        <Footer />
      </DDTheme>
    </div>
  );
};

const MyApp = ({ Component, pageProps }: AppProps) => (
  <StoreProvider initialState={initialState} reducer={reducer}>
    <WrapperApp>
      <Component {...pageProps} />
    </WrapperApp>
  </StoreProvider>
);

export default MyApp;
