import type { AppProps } from "next/app";
import Head from "next/head";
import { useEffect, useState } from "react";
import { DDTheme } from "@cnerylozada/dd.front.react.wp.library";
import { StoreProvider, reducer, initialState } from "../store";
import { Navbar } from "../components";
import { languages } from "../utils";
import "../styles/globals.css";

const MyApp = ({ Component, pageProps }: AppProps) => {
  const [isDarkMode, setIsDarkMode] = useState<boolean>(false);

  useEffect(() => {
    localStorage.setItem("dd-lng", languages.spanish);
  }, []);

  return (
    <div className={`relative ${isDarkMode ? "darkPalette" : ""}`}>
      <Head>
        <title>
          {true
            ? "Dynamic Devs - Desarrollo de Software e Innovación"
            : "Dynamic Devs - Software Development & Innovation"}
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StoreProvider initialState={initialState} reducer={reducer}>
        <DDTheme isDarkMode={isDarkMode}>
          <Navbar setIsDarkMode={setIsDarkMode} />
          <Component {...pageProps} />
        </DDTheme>
      </StoreProvider>
    </div>
  );
};

export default MyApp;
