import type { NextPage } from "next";
import Head from "next/head";
import { DDText } from "@cnerylozada/dd.front.react.wp.library";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-bg2 text-text">
        <DDText size="headline" weight="light">
          Welcome to my dynamic web page !
        </DDText>
        <DDText size="sectionHeadline" weight="bold">
          Abcdefghi
        </DDText>
        <DDText size="subHeadline">Abcdefghi</DDText>
        <DDText size="paragraph" weight="regular">
          Abcdefghi
        </DDText>
        <DDText>Abcdefghi</DDText>
        <DDText size="small">Abcdefghi</DDText>
      </main>
    </div>
  );
};

export default Home;
